import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import Navbar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
          debug flex flex-col h-screen
          `}
      >
        
        <Navbar />
        <div
          className="flex flex-1 overflow-auto 
          bg-[url('/bg.jpg')] bg-cover bg-center debug1
          "
          // style={{
          //   backgroundImage: "url('/bg.jpg')",
          // }}
        >
          {/* Overlay */}
          {/* <div className="absolute inset-0 bg-black/70"></div> */}
          {children}
        </div>
      </body>
    </html>
  );
}
